openapi: 3.0.0
info:
  title: Titans de Sète Rugby API
  version: 1.0.0
  description: API Documentation for the Titans de Sète Rugby Application
servers:
  - url: /R401/r401-App/api
    description: API Server
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: []
paths:
  /endpointJoueur.php:
    get:
      summary: Récupérer un ou plusieurs joueurs
      description: Récupère un joueur spécifique ou tous les joueurs
      operationId: getJoueur
      tags:
        - Joueur
      parameters:
        - name: Authorization
          in: header
          description: Token d'authentification JWT
          required: true
          schema:
            type: string
        - name: Id_Joueur
          in: query
          description: ID du joueur à récupérer
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Joueur trouvé
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        Id_Joueur:
                          type: integer
                        licence:
                          type: string
                        nom:
                          type: string
                        prenom:
                          type: string
                        taille:
                          type: integer
                        poids:
                          type: integer
                        date_naissance:
                          type: string
                          format: date
                        statut:
                          type: string
                        commentaire:
                          type: string
        '401':
          description: Token invalide ou non fourni
        '402':
          description: Token incorrect
        '500':
          description: Erreur interne du serveur
    post:
      summary: Créer un joueur
      description: Ajoute un nouveau joueur
      operationId: createJoueur
      tags:
        - Joueur
      parameters:
        - name: Authorization
          in: header
          description: Token d'authentification JWT
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                licence:
                  type: string
                nom:
                  type: string
                prenom:
                  type: string
                taille:
                  type: integer
                poids:
                  type: integer
                date_naissance:
                  type: string
                  format: date
                statut:
                  type: string
                commentaire:
                  type: string
      responses:
        '200':
          description: Joueur créé
        '401':
          description: Requête invalide ou token non fourni
        '402':
          description: Token incorrect
        '500':
          description: Erreur interne du serveur
    put:
      summary: Mettre à jour un joueur
      description: Met à jour les informations d'un joueur existant
      operationId: updateJoueur
      tags:
        - Joueur
      parameters:
        - name: Authorization
          in: header
          description: Token d'authentification JWT
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Id_Joueur:
                  type: integer
                licence:
                  type: string
                nom:
                  type: string
                prenom:
                  type: string
                taille:
                  type: integer
                poids:
                  type: integer
                date_naissance:
                  type: string
                  format: date
                statut:
                  type: string
                commentaire:
                  type: string
      responses:
        '200':
          description: Joueur mis à jour
        '401':
          description: Requête invalide ou token non fourni
        '402':
          description: Token incorrect
        '500':
          description: Erreur interne du serveur
    delete:
      summary: Supprimer un joueur
      description: Supprime un joueur existant
      operationId: deleteJoueur
      tags:
        - Joueur
      parameters:
        - name: Authorization
          in: header
          description: Token d'authentification JWT
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Id_Joueur:
                  type: integer
      responses:
        '200':
          description: Joueur supprimé
        '401':
          description: Requête invalide ou token non fourni
        '402':
          description: Token incorrect
        '500':
          description: Erreur interne du serveur
